import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { AppLayoutShell } from "@/components/app-layout-shell";
import { getServerAuthSession } from "@/lib/auth";
import { AppProviders } from "@/providers/app-providers";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerAuthSession();

  return (
    <html lang="es" suppressHydrationWarning>
      <body className={`${poppins.variable} font-sans antialiased`}>
        <AppProviders session={session}>
          <AppLayoutShell
            user={
              session?.user
                ? {
                    email: session.user.email,
                    image: session.user.image,
                    name: session.user.name,
                    registrado: session.user.registrado,
                  }
                : null
            }
          >
            {children}
          </AppLayoutShell>
        </AppProviders>
      </body>
    </html>
  );
}
